# -*- coding: utf-8 -*-
"""Shiori Hikita Python 2 Final Project Fall 2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fUClrvGNG3uhYXwC0bVOcnFPihr-lWx

# 📊 Final Project: (Olympics number of medal of US)



## 👩🏽‍💻 Student Information

- **Name: (Shiori Hikita)**  
- **Dataset Used: (https://tinyurl.com/GWC-olympics)**
- **Data Source URL (if applicable):**

---

## 🔍 Step 1: Define Your Data Question


When, where, and what sports did US took the most numbers of medal?
"""

# 📥 Step 2: Import Libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Optional: Set a Seaborn theme for clean visuals
# Example:**
# sns.set_theme(style="whitegrid")

# 📂 Step 3: Load the Dataset
# You can pick your own dataset! --> Look at Kaggle: https://www.kaggle.com/

# Seaborn Dataset
# df = sns.load_dataset("your_dataset_name") # e.g., "tips", "diamonds", "mpg"
# df.head()

# Olympics Dataset/Kaggle
# df = pd.read_csv("your_dataset_url", skiprows=5)
# df.head()

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]

csv = "https://tinyurl.com/GWC-olympics"
df = pd.read_csv(csv, skiprows = 5)

"""## 🧼 Step 4: Clean and Filter the Data

Use NumPy and Pandas to filter the dataset based on your question. This could include:
- Dropping missing values
- Filtering rows by a condition
- Creating new columns
"""

# Example: Filtering for rows with mpg > 20
# filtered_df = df[df["mpg"] > 20]

# Your filtering and cleaning code here:
df = df.drop(df.columns[3], axis = 1)
df = df.drop(df.columns[3], axis = 1)
df = df.drop(df.columns[4], axis = 1)
df = df.drop(df.columns[4], axis = 1)
df = df.drop(df.columns[4], axis = 1)
df.head()

"""## 📊 Step 5: Visualization #1

Write a short sentence about what this graph is showing.

(Insert here)

When did the US took the most number of medal?

X-axis shows the year and Y-axis shows the number of medal the US took.
"""

# Plot #1 code here (e.g., line plot, bar chart, scatter plot)

plt.figure(figsize=(8, 5))
# sns.lineplot(...)
usa_medal = df[(df["NOC"] == "USA")]

medal_counts_year = usa_medal.groupby("Year").size()

plt.plot(medal_counts_year.index, medal_counts_year.values, color = 'blue')

plt.title("US number of medal in a year")
plt.xlabel("Year")
plt.ylabel("Number of Medal")
plt.show()

"""### Insight from Plot #1:
What did you observe? Any surprising trends or patterns?

(Insert here)

1904 was the year that the US had the most number of medals. Also, 1984 was the second most. It looks like increasing but it may be because the changes of the numbers of sports

## 📊 Step 6: Visualization #2

Describe what this graph is showing and why you chose it.

(Insert here)

Where did the US took the most number of medal?

I'm using a bar graph because there are not changing in time.
"""

# Plot #2 code here
plt.figure(figsize=(8, 5))

medal_counts_city = usa_medal.groupby("City").size()

medal_counts_city.plot(kind = "bar", color = "red", edgecolor = "black")

plt.title("US number of medal in a city")
plt.xlabel("City")
plt.ylabel("Number of Medal")
plt.xticks(rotation = 45, ha = "right")

plt.show()

"""### Insight from Plot #2:
What does this visualization tell you about your question?

(Insert here)

The US got the most numbers of medal in Los Angeles, and the second most in St Louis. The number of medal will change when there is a olympic more than one time in a same place so this graph shows how much medal the US took in the city total.

## 📊 Step 7: Visualization #3

Explain what you're comparing or analyzing in this chart.

(Insert here)

What sport did the US have the medal best?

First graph is the total and the second graph is the number of medal only in the 2004.
"""

# Plot #3 code here

plt.figure(figsize=(8, 5))

medal_counts_sport = usa_medal.groupby("Sport").size()

medal_counts_sport.plot(kind = "bar", color = "green", edgecolor = "black")

plt.title("US number of medal in sports")
plt.xlabel("Sport")
plt.ylabel("Number of Medal")
plt.xticks(rotation = 45, ha = "right")

plt.show()

plt.figure(figsize=(8, 5))

usa_medal_2004 = df[(df["NOC"] == "USA") & (df["Year"] == 2004)]

medal_counts_sport_2004 = usa_medal_2004.groupby("Sport").size()

medal_counts_sport_2004.plot(kind = "bar", color = "yellow", edgecolor = "black")

plt.title("US number of medal in sports (2004)")
plt.xlabel("Sport")
plt.ylabel("Number of Medal")
plt.xticks(rotation = 45, ha = "right")

plt.show()

"""### Insight from Plot #3:
What does this visualization tell you about your question?

(Insert here)

This shows that the US have the most medal in aquatics.

The first graph shows that the athletics have a close numbers of medal but in the second graph, aquatics takes more than twice medals than the athletics.

## 🧠 Step 8: Final Analysis

Answer your original question based on the visualizations.

- What did you find out?
- What might you want to explore next?
- Did anything surprise you?

Feel free to add a final conclusion paragraph here.

I find out that
 - 1904 and 1984 had the high numbers of medal
 - There are more medal when it was held in the US
 - Aquatics get the most numbers of medal in the US

I want to explore
 - What happened in the 1904 and 1984
   - It was held in St Louis and Los Angeles
   - In the 1904, the number of sports increased
   - In the 1984, the Soviet Union and its alies decided not to paricipate in the Olympic

## 🌟 Optional: Research

Use Google to find one reason or context behind a trend you noticed.

**Example:**  
"Why did fuel efficiency improve dramatically in 1980?"

Paste a short summary or bullet points of your findings here.

## ✅ Submission Checklist

- [ ] I included **3+ visualizations**
- [ ] I used **NumPy or Pandas to filter my data**
- [ ] I answered a data question
- [ ] I included insights for each graph
- [ ] My code runs without errors

---

Good luck and have fun telling your data story! 🎉
"""